# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bom',
                'doc_host': 'https://janhesse53.github.io',
                'git_url': 'https://github.com/janhesse53/bom',
                'lib_path': 'bom'},
  'syms': {'bom.core': {'bom.core.foo': ('core.html#foo', 'bom/core.py')}}}
